id: mobtexting
org: mobtexting
name: whatsapp
region: ap-south-1
ignore:
  - database
  - docker
  - scripts
  - resources/themes/tabler/assets
  - resources/assets
  - storage/geoip
  - git
  - pull
  - optimize
  - tag
  - tests
  - "*.dat"
  - "*.mmdb"
  - vendor/*.js
  - vendor/pragmarx/support/src/GeoIp/GeoLiteCity.dat
  - vendor/pragmarx/support/src/GeoIp/GeoLite2-City.mmdb
  - .env.docker
environments:
  production:
    memory: 1024
    cli-memory: 512
    #runtime: php-7.4:2la
    runtime: docker
    #cmd: null #Specifies parameters that you want to pass in with ENTRYPOINT.
    #entry-point: null #Specifies the entry point to their application, which is typically the location of the runtime executable.
    #working-dir: /var/task
    assets: com.whatsapp.ap-south-1.assets
    asset-bucket: true # create aws bucket
    warm: 10
    timeout: 30
    scheduler: false
    queues: false
    cloudfront: false
    volumes:
      - /mnt/storage:fsap-0a31095162dd0ca44
    subnets:
      - subnet-xxxx
    security-groups:
      - sg-xxx
    build:
      - "COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_MIRROR_PATH_REPOS=1 COMPOSER=composer.json composer install --no-dev --prefer-dist --classmap-authoritative"
      - "php artisan event:cache"
      - "php artisan route:cache"
  staging:
    memory: 512
    cli-memory: 512
    #runtime: php-7.4:2la
    runtime: docker
    assets: true
    timeout: 30
    scheduler: false
    queues: false
    cloudfront: false
    volumes:
      - /mnt/storage:fsap-0a31095162dd0ca44
    subnets:
      - subnet-xxxx
    security-groups:
      - sg-xxx
    build:
      - "COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_MIRROR_PATH_REPOS=1 COMPOSER=composer.json composer install --no-dev --prefer-dist --no-interaction --classmap-authoritative"
      - "php artisan event:cache"
      - "php artisan route:cache"
